Repository apify/apify-zapier-integration, pull requests merged in 2025-08, with the labels that each got.

#87 feat: use waitForRunToFinish across creates actions
  package.json
  src/consts.js
  src/creates/actor_run.js
  src/creates/scrape_single_url.js
  src/creates/task_run.js
  test/creates/actor_run.js
  test/creates/scrape_single_url.js
Labels: tested, t-integrations

#90 feat: Improve getting runs with multiple statuses
  src/triggers/actor_run_finished.js
  src/triggers/task_run_finished.js
  test/triggers/actor_run_finished.js
  test/triggers/task_run_finished.js
Labels: tested, t-integrations

#91 hotfix: Fix publish workflow
  .github/workflows/publish.yml
Labels: adhoc

#96 chore: remove options from signed url
  src/apify_helpers.js
Labels: adhoc, t-integrations
